workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter packages get
      - name: Verify configuration
        script: flutter pub get
      - name: Build App Bundle / Test
        script: |
          flutter build ios --simulator --release
artifacts:
  - build/ios/iphonesimulator/*.app